name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - main
      - main2
  pull_request:
    branches:
      - main
      - main2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      working-directory: .
      run: mvn clean package -DskipTests
      
    - name: Docker Compose Build Application
      working-directory: ./deploy/docker
      run: docker compose build

    - name: Debug environment variables
      run: |
       echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
       echo "GITHUB_RUN_ID=${{ github.run_id }}"
      
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{secrets.DOCKER_USERNAME}}/rest-with-spring-boot-musashifraco:latest ${{secrets.DOCKER_USERNAME}}/rest-with-spring-boot-musashifraco:${{github.run_id}}
        docker push ${{secrets.DOCKER_USERNAME}}/rest-with-spring-boot-musashifraco:${{github.run_id}}
        docker push ${{secrets.DOCKER_USERNAME}}/rest-with-spring-boot-musashifraco:latest
